project_name: loki-proxy
builds:
  -
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
dockers:
  -
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - 'public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Version }}-amd64'
  -
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
    image_templates:
      - 'public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Version }}-arm64v8'
docker_manifests:
  - 
    name_template: 'public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Version }}'
    image_templates:
      - 'public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Version }}-arm64v8'
checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums'
changelog:
  use: github-native
snapshot:
  name_template: '{{ incpatch .Version }}-next'
