project_name: loki-proxy
builds:
  -
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "public.ecr.aws/groundcovercom/{{ .ProjectName }}:{{ .Tag }}"

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums'
changelog:
  use: github-native
snapshot:
  name_template: "{{ incpatch .Version }}-next"
