apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki-proxy.fullname" . }}-config
  labels:
    {{- include "loki-proxy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 6 }}
